version: '3'

services:
  cliente:
    container_name: cliente
    build: ../cliente/
    environment:
      - kafka=kafka
    ports:
      - 3000:3000

  servidor:
    container_name: servidor
    build: ../servidor/
    environment:
      - kafka=kafka
    ports:
      - 3001:3001

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181

  kafka:
    container_name: kafka-server
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - 9092:9092